// Parity harness for the TypeScript corpus/ port (spine.ts + chapters.ts)
// against the Python pipeline originals (stage1_greek.parse_spine,
// stage1_chapters.extract_chapters_grc), on real Metaphysics data.
//
// 1. Bundles spine.ts + chapters.ts for Node via esbuild.
// 2. Reads the SAME cached Diogenes export XML + grc TEI the Python goldens
//    were generated from, runs the TS port on them.
// 3. Diffs against goldens pre-generated by a Python driver (see the
//    scratchpad gen_goldens.py) — segments/columns/line numbers/text must
//    match EXACTLY, plus chapter anchors (book, chapter, column, line,
//    wordIndex, bookstart).
//
// All paths are env-overridable; the harness SKIPS (exit 0, clear message)
// when the cached export or the goldens are absent, since neither is
// committed to the repo (copyright / build-output reasons).
//
// Usage: node scripts/parity-corpus.mjs

import { build } from 'esbuild';
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { load as yamlLoad } from 'js-yaml';

const here = path.dirname(fileURLToPath(import.meta.url));
const workbenchRoot = path.resolve(here, '..');
const worktreeRoot = path.resolve(workbenchRoot, '..');
const mainCheckout = process.env.ARISTOTLE_MAIN_CHECKOUT
  ?? '/Users/johnboyer/Developer/aristotle-reader';
const scratchDir = process.env.CORPUS_PARITY_SCRATCH
  ?? '/private/tmp/claude-501/-Users-johnboyer-Developer-aristotle-reader--claude-worktrees-blissful-rubin-d64797/e1c8be9d-8f51-4b23-9dcf-e914f359a134/scratchpad';

const xmlPath = process.env.CORPUS_PARITY_XML
  ?? path.join(mainCheckout, 'build/export/Diogenes-Resources/xml/tlg/tlg0086025.xml');
const grcTeiPath = process.env.CORPUS_PARITY_GRC_TEI
  ?? path.join(worktreeRoot, 'sources/tlg0086.tlg025.perseus-grc2.xml');
const manifestPath = process.env.CORPUS_PARITY_MANIFEST
  ?? path.join(worktreeRoot, 'manifests/Meta.yaml');
const goldenSpinePath = process.env.CORPUS_PARITY_GOLDEN_SPINE
  ?? path.join(scratchDir, 'golden-spine.json');
const goldenChaptersPath = process.env.CORPUS_PARITY_GOLDEN_CHAPTERS
  ?? path.join(scratchDir, 'golden-chapters.json');
const goldenDiogenesCmdPath = process.env.CORPUS_PARITY_GOLDEN_DIOGENES
  ?? path.join(scratchDir, 'golden-diogenes-cmd.json');

function skip(msg) {
  console.log(`SKIP: ${msg}`);
  process.exit(0);
}

for (const [label, p] of [
  ['cached Diogenes export XML', xmlPath],
  ['grc TEI', grcTeiPath],
  ['Meta manifest', manifestPath],
  ['golden spine', goldenSpinePath],
  ['golden chapters', goldenChaptersPath],
]) {
  if (!existsSync(p)) skip(`${label} not found at ${p} — run the scratchpad gen_goldens.py driver first`);
}

// ── bundle the TS corpus port for Node ──────────────────────────────────────
const scratch = mkdtempSync(path.join(tmpdir(), 'corpus-parity-'));
const bundle = path.join(scratch, 'corpus.mjs');
await build({
  entryPoints: [path.join(workbenchRoot, 'src/lib/corpus/parity-entry.ts')],
  bundle: true,
  format: 'esm',
  platform: 'node',
  outfile: bundle,
  logLevel: 'silent',
});
const { parseSpine, extractChaptersGrc, buildDiogenesExportCommand } =
  await import(pathToFileURL(bundle).href);

// ── manifest ─────────────────────────────────────────────────────────────
const manifestYaml = yamlLoad(readFileSync(manifestPath, 'utf-8'));
const spineManifest = {
  work_id: manifestYaml.work.id,
  greek_edition: manifestYaml.work.greek_edition,
  citation_scheme: manifestYaml.citation?.scheme,
  books: manifestYaml.books,
};

// ── spine parity ─────────────────────────────────────────────────────────
const xml = readFileSync(xmlPath, 'utf-8');
const tsSpine = parseSpine(xml, spineManifest);
const goldenSpine = JSON.parse(readFileSync(goldenSpinePath, 'utf-8'));

let hard = 0;
const diffs = [];
function reportDiff(msg) {
  hard++;
  if (diffs.length < 25) diffs.push(msg);
}

if (tsSpine.work !== goldenSpine.work) reportDiff(`work: ts=${tsSpine.work} py=${goldenSpine.work}`);
if (tsSpine.edition !== goldenSpine.edition) reportDiff(`edition: ts=${tsSpine.edition} py=${goldenSpine.edition}`);

const segCountMatch = tsSpine.segments.length === goldenSpine.segments.length;
if (!segCountMatch) reportDiff(`segment count: ts=${tsSpine.segments.length} py=${goldenSpine.segments.length}`);

let lineCompares = 0;
const segN = Math.min(tsSpine.segments.length, goldenSpine.segments.length);
for (let i = 0; i < segN; i++) {
  const ts = tsSpine.segments[i], py = goldenSpine.segments[i];
  if (ts.id !== py.id || ts.book !== py.book || ts.column !== py.column) {
    reportDiff(`segment[${i}] key: ts=${ts.id}/${ts.book}/${ts.column} py=${py.id}/${py.book}/${py.column}`);
    continue;
  }
  if (ts.lines.length !== py.lines.length) {
    reportDiff(`segment ${ts.id}: line count ts=${ts.lines.length} py=${py.lines.length}`);
    continue;
  }
  for (let j = 0; j < ts.lines.length; j++) {
    lineCompares++;
    const tl = ts.lines[j], pl = py.lines[j];
    if (tl.n !== pl.n || tl.text !== pl.text || Boolean(tl.joined) !== Boolean(pl.joined)) {
      reportDiff(`segment ${ts.id} line[${j}]: ts=${JSON.stringify(tl)} py=${JSON.stringify(pl)}`);
    }
  }
}

if (tsSpine.headings.length !== goldenSpine.headings.length) {
  reportDiff(`headings count: ts=${tsSpine.headings.length} py=${goldenSpine.headings.length}`);
} else {
  for (let i = 0; i < tsSpine.headings.length; i++) {
    const th = tsSpine.headings[i], ph = goldenSpine.headings[i];
    if (th.column !== ph.column || th.text !== ph.text) {
      reportDiff(`heading[${i}]: ts=${JSON.stringify(th)} py=${JSON.stringify(ph)}`);
    }
  }
}

if (tsSpine.unassigned_lines.length !== goldenSpine.unassigned_lines.length) {
  reportDiff(`unassigned_lines count: ts=${tsSpine.unassigned_lines.length} py=${goldenSpine.unassigned_lines.length}`);
}

console.log(`spine: ${segN} segments compared (ts=${tsSpine.segments.length} py=${goldenSpine.segments.length}), `
  + `${lineCompares} lines compared, ${tsSpine.headings.length} headings, `
  + `${tsSpine.unassigned_lines.length} unassigned`);

// ── chapters parity ─────────────────────────────────────────────────────
const grcXml = readFileSync(grcTeiPath, 'utf-8');
const chaptersCfg = manifestYaml.chapters;
const tsChapters = extractChaptersGrc(tsSpine, grcXml, {
  chapterSubtype: chaptersCfg.chapter_subtype ?? 'chapter',
  bookSubtype: chaptersCfg.book_subtype ?? 'book',
  chapterMarker: chaptersCfg.chapter_marker ?? 'div',
  topBook: chaptersCfg.grc_book ?? null,
  extra: chaptersCfg.extra ?? null,
});
const goldenChapters = JSON.parse(readFileSync(goldenChaptersPath, 'utf-8'));

let chapterDiffs = 0;
if (tsChapters.length !== goldenChapters.length) {
  reportDiff(`chapters count: ts=${tsChapters.length} py=${goldenChapters.length}`);
  chapterDiffs++;
}
const chN = Math.min(tsChapters.length, goldenChapters.length);
for (let i = 0; i < chN; i++) {
  const tc = tsChapters[i], pc = goldenChapters[i];
  const same = tc.book === pc.book && tc.chapter === pc.chapter && tc.column === pc.column
    && tc.line === pc.line && tc.wordIndex === pc.wordIndex && tc.bookstart === pc.bookstart;
  if (!same) {
    reportDiff(`chapter[${i}]: ts=${JSON.stringify(tc)} py=${JSON.stringify(pc)}`);
    chapterDiffs++;
  }
}
console.log(`chapters: ${chN} compared (ts=${tsChapters.length} py=${goldenChapters.length}), diffs=${chapterDiffs}`);

// ── Diogenes command-construction parity (if golden present) ───────────────
if (existsSync(goldenDiogenesCmdPath)) {
  const goldenCmd = JSON.parse(readFileSync(goldenDiogenesCmdPath, 'utf-8'));
  const diogenesManifest = {
    work: { tlg_author: manifestYaml.work.tlg_author },
    sources: {
      diogenes_server: manifestYaml.sources.diogenes_server,
      tlg_dir_env: manifestYaml.sources.tlg_dir_env,
      tlg_dir_default: manifestYaml.sources.tlg_dir_default,
    },
  };
  // Same EXPORT_DIR the Python used: <repo root>/build/export (worktree root).
  const exportDir = path.join(worktreeRoot, 'build', 'export');
  const tsCmd = buildDiogenesExportCommand(
    diogenesManifest,
    exportDir,
    worktreeRoot,
    (name) => process.env[name],
  );
  const cmdMatch = JSON.stringify(tsCmd.cmd) === JSON.stringify(goldenCmd.cmd);
  const cwdMatch = tsCmd.cwd === goldenCmd.cwd;
  const envMatch = tsCmd.env.TLG_DIR === goldenCmd.env.TLG_DIR && tsCmd.env.PATH === goldenCmd.env.PATH;
  if (!cmdMatch || !cwdMatch || !envMatch) {
    reportDiff(`diogenes cmd: ts=${JSON.stringify(tsCmd)} py=${JSON.stringify(goldenCmd)}`);
  }
  console.log(`diogenes command: ${cmdMatch && cwdMatch && envMatch ? 'match' : 'MISMATCH'}`);
} else {
  console.log('diogenes command golden not found — skipping that comparison');
}

// ── report ───────────────────────────────────────────────────────────────
if (diffs.length) {
  console.log(`\nfirst ${diffs.length} diffs:`);
  for (const d of diffs) console.log(`  ✗ ${d}`);
}
console.log(`\ntotal hard mismatches: ${hard}`);
process.exit(hard ? 1 : 0);
