"""Generate docs/front-matter.md from the sigla files.

The reference document is GENERATED so it cannot drift from the data the checks
actually use. `work/sigla/work-sigla.json` is the authority for the work sigla;
`work/sigla/apparatus-sigla.json` for the editor and zoological sigla. Edit
those, then run this.

    python3 -m bonitz_pipeline.front_matter_doc            # check, writes nothing
    python3 -m bonitz_pipeline.front_matter_doc --write

⚠ THE DOCUMENT IS A REFERENCE, NOT THE DIPLOMATIC TRANSCRIPTION. Titles are
given in full — Bonitz prints `— ὕστερα` for a repeated title, which is clear
on the leaf and confusing anywhere else. Where the leaf differs from the
reference form the entry carries a `printed` field, and those four rows are
listed together at the end so nothing is lost.
"""

from __future__ import annotations

import argparse
import json
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WORKS = ROOT / 'work' / 'sigla' / 'work-sigla.json'
APPARATUS = ROOT / 'work' / 'sigla' / 'apparatus-sigla.json'
DOC = ROOT / 'docs' / 'front-matter.md'

KAI = 'ϗ' + '̀'


def _rows_works(works: list[dict]) -> list[str]:
    out = []
    for e in works:
        title = unicodedata.normalize('NFC', e['title'])
        bekker = (e.get('bekker') or '—').replace('-', '–')
        out.append(f'| `{e["siglum"]}` | {title} | {bekker} |')
    return out


def _rows_apparatus(entries: dict) -> list[str]:
    out = []
    for sig, v in entries.items():
        if isinstance(v, str):
            out.append(f'| `{sig}` | {v} |')
            continue
        bits = []
        if v.get('who'):
            bits.append(v['who'])
        bits += list(v.get('works') or [])
        if v.get('note'):
            bits.append(v['note'])
        also = f' (also `{v["also"]}`)' if v.get('also') else ''
        out.append(f'| `{sig}`{also} | ' + '. '.join(bits) + ' |')
    return out


def render() -> str:
    works = json.loads(WORKS.read_text(encoding='utf-8'))['works']
    app = json.loads(APPARATUS.read_text(encoding='utf-8'))
    printed = [e for e in works if e.get('printed')]

    L: list[str] = []
    a = L.append
    a('<!-- GENERATED by bonitz_pipeline.front_matter_doc — do not edit by hand.')
    a('     Edit work/sigla/work-sigla.json or apparatus-sigla.json, then rerun. -->')
    a('')
    a('# Bonitz, *Index Aristotelicus* — sigla reference')
    a('')
    a('Every abbreviation Bonitz defines before the index proper. Source is the')
    a('1870 Berlin original (archive.org `aristotelisopera05arisuoft`, leaves')
    a('261, 262, 264) at ~415 ppi. Provenance, reader comparison and the')
    a('measurements behind this are in `work/frontmatter/NOTES.md`.')
    a('')
    a('Titles are given **in full**. Bonitz prints an em dash for a repeated')
    a('title; that is clear on the leaf and confusing here. The four rows whose')
    a('printed form differs are listed at the end.')
    a('')
    a('---')
    a('')
    a(f'## Work sigla ({len(works)} rows, '
      f'{len({e["siglum"] for e in works})} distinct)')
    a('')
    a('A citation siglum is **work + book numeral**: `Ζιι` is `Ζι` + book ι,')
    a('`πκγ` is `π` + book κγ = 23. A vowel inside a siglum is either part of')
    a('the work siglum or a book numeral, never anything else.')
    a('')
    a('⚠ A **bare book letter inherits the previous citation\'s work**.')
    a('`Ζιε13. 544a32. ζ1. 558b13` is HA book 6, not the work `ζ`. The Bekker')
    a('page adjudicates.')
    a('')
    a('⚠ **Metaphysics book letters are names, not numerals** — Α α Β Γ … Μ Ν.')
    a('')
    a('| siglum | title | Bekker |')
    a('|---|---|---|')
    L += _rows_works(works)
    a('')
    a('---')
    a('')
    a(f'## Editors and interpreters ({len(app["editors_p11"])})')
    a('')
    a('Printed VII. Bonitz: *Editores et interpretes librorum Aristetolicorum')
    a('his siglis significavimus* — `Aristetolicorum` is his compositor\'s')
    a('transposition, kept as printed.')
    a('')
    a('| siglum | edition |')
    a('|---|---|')
    L += _rows_apparatus(app['editors_p11'])
    a('')
    a('Fragment editions: elegiac and lyric poets **Bergk** (ed. III, Lips.')
    a('1866), tragedians **Nauck**, comedians **Meineke**, philosophers')
    a('**Mullach** (Paris 1860).')
    a('')
    a('---')
    a('')
    a(f'## Zoological and botanical authorities ({len(app["zoological_p12"])})')
    a('')
    a('Printed VIII. Four entries (`Harvey`, `Hehn`, `Heldreich`,')
    a('`Sonnenburg`) print the author\'s name itself as the siglum.')
    a('')
    a('| siglum | work |')
    a('|---|---|')
    L += _rows_apparatus(app['zoological_p12'])
    a('')
    a('---')
    a('')
    a('## Where the leaf differs from the reference form')
    a('')
    a('| siglum | printed | reference |')
    a('|---|---|---|')
    for e in printed:
        a(f'| `{e["siglum"]}` | {e["printed"]} | {e["title"]} |')
    a('')
    a('`Η` prints a bare eta — no smooth breathing — where every other capital')
    a('on the leaf carries its mark (`Ὕπνȣ`, `Ἀλέξανδρον`, `Ἑρμηνείας`).')
    a('')
    a('## Conventions')
    a('')
    a(f'- The kai abbreviation always carries a **grave**: `{KAI}`, never bare.')
    a('  The corpus agrees 760 of 785.')
    a('- `ȣ` is a single sort. Never `ου`, never a bare `υ`.')
    a('- A circumflex over `ȣ` is U+0342 perispomeni, not U+0303.')
    a('- No stigma (ϛ) occurs anywhere in the front matter. Every sigma-family')
    a('  character here is a final sigma ς.')
    return '\n'.join(L) + '\n'


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--write', action='store_true')
    args = ap.parse_args(argv)
    text = render()
    if args.write:
        DOC.parent.mkdir(parents=True, exist_ok=True)
        DOC.write_text(text, encoding='utf-8')
        print(f'wrote {DOC} ({len(text.splitlines())} lines)')
        return 0
    current = DOC.read_text(encoding='utf-8') if DOC.exists() else ''
    if current == text:
        print('docs/front-matter.md is up to date')
        return 0
    print('docs/front-matter.md is STALE — rerun with --write')
    return 1


if __name__ == '__main__':
    sys.exit(main())
