"""The diplomatic transcription as one readable document.

Until now the text existed only as 96 per-column files and some ALTO XML, so
there was nothing a person or an agent could read straight through, quote from,
or grep. This assembles them — generated, never hand-edited, so it follows the
corpus automatically every time a ruling is applied.

    python3 -m bonitz_pipeline.transcription_doc            # check, writes nothing
    python3 -m bonitz_pipeline.transcription_doc --write

⚠ DIPLOMATIC. What is here is what Bonitz's compositor set, including his
errors. `ἄνθρώπȣ` really does carry two accents on page 60; `ἀπόπλ` really does
end in a lambda. Corrections belong in the corrigenda register, never in this
text. Do not "fix" anything you read here.

⚠ TWO STAGES, AND THE DIFFERENCE MATTERS. Pages in `work/reconciled` are
adjudicated and applied. Pages in `work/reconciled-auto` are settled but not
yet promoted — John has ruled them, the rulings are written, and the promotion
is still his to make. Each page says which it is, because quoting an unpromoted
page as settled fact is exactly the overreach this project keeps catching.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .normalize import CORPUS_STAGES, corpus_columns

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / 'docs' / 'transcription.md'

STAGE_NOTE = {
    'reconciled': 'applied',
    'reconciled-auto': 'settled, awaiting promotion',
}


def render() -> str:
    cols = corpus_columns()
    by_page: dict[int, list[Path]] = {}
    for c in cols:
        by_page.setdefault(int(c.stem.split('-')[1]), []).append(c)

    lines = 0
    for c in cols:
        lines += len(c.read_text(encoding='utf-8').splitlines())

    L: list[str] = [
        '<!-- GENERATED by bonitz_pipeline.transcription_doc — do not edit by',
        '     hand. Edit the corpus, then rerun. -->',
        '',
        '# Bonitz, *Index Aristotelicus* — diplomatic transcription',
        '',
        f'{len(by_page)} pages, {len(cols)} columns, {lines} printed lines.',
        '',
        '**This records what was printed, not what should have been.** Bonitz\'s',
        'compositor errors stand as set — `ἄνθρώπȣ` carries two accents at',
        '60-L:46, `ἀπόπλ` ends in a lambda at 56-L:22. Corrections live in the',
        'corrigenda register, never in this text.',
        '',
        'One line here is one printed line. A hyphen at end of line is the',
        'compositor\'s, and the word continues on the next. `ȣ` is the',
        'ou-ligature and `ϗ̀` the kai abbreviation, both single sorts; they are',
        'never expanded. See `docs/front-matter.md` for the sigla.',
        '',
        '| stage | meaning |',
        '|---|---|',
        '| applied | adjudicated, rulings written to the corpus |',
        '| settled, awaiting promotion | ruled and written, promotion still John\'s call |',
        '',
    ]

    for page in sorted(by_page):
        for col in sorted(by_page[page], key=lambda p: p.stem):
            side = col.stem.split('-')[2]
            stage = STAGE_NOTE.get(col.parent.name, col.parent.name)
            L += ['---', '', f'## Page {page}, column {side}', '',
                  f'*{stage}*', '', '```text']
            for n, line in enumerate(
                    col.read_text(encoding='utf-8').splitlines(), 1):
                L.append(f'{n:>3}  {line}')
            L += ['```', '']
    return '\n'.join(L) + '\n'


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--write', action='store_true')
    a = ap.parse_args(argv)
    text = render()
    if a.write:
        DOC.parent.mkdir(parents=True, exist_ok=True)
        DOC.write_text(text, encoding='utf-8')
        print(f'wrote {DOC} ({len(text.splitlines())} lines, '
              f'{len(text) / 1024:.0f} KB)')
        return 0
    current = DOC.read_text(encoding='utf-8') if DOC.exists() else ''
    if current == text:
        print('docs/transcription.md is up to date')
        return 0
    print('docs/transcription.md is STALE — rerun with --write')
    return 1


if __name__ == '__main__':
    sys.exit(main())
